### ISSUE TITLE
Compile error on Ubuntu 18.04

### ISSUE THREAD

**Issue by rkorn86** [husisusi/officeonlin-install.sh#196]
My config so far is:
```
lo_src_tag='cp-6.2-5'
lo_dir="/opt/libreoffice"
poco_version=1.9.4
lool_src_tag='CODE-4.2.0-6'
lool_dir="/opt/lool"
lool_configure_opts='--with-lokit-path=/opt/libreoffice/include'
```

Im building inside a Docker Container:
```
FROM ubuntu:18.04

COPY officeonline-install.cfg /etc/loolwsd/

RUN \
  apt update && \
  apt-get -y install git curl sudo wget cpio build-essential libcap-dev libpam0g-dev npm && \
  npm install -g npm

RUN \
  git clone https://github.com/husisusi/officeonlin-install.sh.git /install
  
WORKDIR /install

RUN ./officeonline-install.sh
```

I'm getting the following error, while trying to compile on Ubuntu 18.04:
```
In file included from kit/ChildSession.cpp:39:0:
 kit/KitHelper.hpp: In function 'std::__cxx11::string LOKitHelper::kitCallbackTypeToString(int)':
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_REFERENCE_MARKS' not handled in switch [-Werror=switch]
          switch (static_cast<LibreOfficeKitCallbackType>(type))
                 ^
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_JSDIALOG' not handled in switch [-Werror=switch]
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_CALC_FUNCTION_LIST' not handled in switch [-Werror=switch]
In file included from kit/Kit.cpp:61:0:
 kit/KitHelper.hpp: In function 'std::__cxx11::string LOKitHelper::kitCallbackTypeToString(int)':
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_REFERENCE_MARKS' not handled in switch [-Werror=switch]
          switch (static_cast<LibreOfficeKitCallbackType>(type))
                 ^
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_JSDIALOG' not handled in switch [-Werror=switch]
 kit/KitHelper.hpp:50:16: error: enumeration value 'LOK_CALLBACK_CALC_FUNCTION_LIST' not handled in switch [-Werror=switch]
cc1plus: all warnings being treated as errors
 make[2]: *** [kit/loolwsd_fuzzer-ChildSession.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
 Makefile:1555: recipe for target 'kit/loolwsd_fuzzer-ChildSession.o' failed
 cc1plus: all warnings being treated as errors
 make[2]: *** [kit/loolwsd_fuzzer-Kit.o] Error 1
 Makefile:1583: recipe for target 'kit/loolwsd_fuzzer-Kit.o' failed
 make[2]: Leaving directory '/opt/lool'
 make[1]: *** [all-recursive] Error 1
 Makefile:1984: recipe for target 'all-recursive' failed
 make[1]: Leaving directory '/opt/lool'
 make: *** [all] Error 2
 Makefile:879: recipe for target 'all' failed
 make: Leaving directory '/opt/lool'
```

Is my config wrong or anything else?

**Comment by Ark74** [comment]
I believe your issue is not Ubuntu, but how docker work on building environments.
Or maybe some dependencies not being resolved.

**Comment by rkorn86** [comment]
Fixed by `--disable-werror`, so my config looks like this now:
```
lo_src_tag='cp-6.2-5'
lo_dir="/opt/libreoffice"
poco_version=1.9.4
lool_src_tag='CODE-4.2.0-6'
lool_dir="/opt/lool"
lool_configure_opts='--disable-werror --with-lokit-path=/opt/libreoffice/include'
```

Next error on missing requirement is `ImportError: No module named polib` will start next build with added `python-polib`:
```
FROM ubuntu:18.04

COPY officeonline-install.cfg /etc/loolwsd/

RUN \
  apt update && \
  apt-get -y install git curl sudo wget cpio build-essential libcap-dev libpam0g-dev npm python-polib && \
  npm install -g npm

RUN \
  git clone https://github.com/husisusi/officeonlin-install.sh.git /install
  
WORKDIR /install

RUN ./officeonline-install.sh
```

Lets have a look whats the next error in 1 hour. :weary:

**Comment by rkorn86** [comment]
Got it. Compile time 01:48:00. :tada: 

**officeonline-install.cfg**:
```
lo_src_tag='cp-6.2-5'
lo_dir="/opt/libreoffice"
lo_non_free_ttf=true
poco_version=1.9.4
lool_src_tag='CODE-4.2.0-6'
lool_dir="/opt/lool"
lool_configure_opts='--disable-werror --with-lokit-path=/opt/libreoffice/include'
```

**Dockerfile**:
```
##
# Build LibreOffice Core, LibreOffice Online & Poco
#
FROM ubuntu:18.04

# Copy configuration file
COPY officeonline-install.cfg /etc/loolwsd/

# Install build dependencies
RUN \
  apt update && \
  apt-get -y install git curl sudo wget cpio build-essential libcap-dev libpam0g-dev npm python-polib python-lxml && \
  npm install -g npm

# Clone script to install Office Online on Ubuntu 18.04
RUN \
  git clone https://github.com/husisusi/officeonlin-install.sh.git /install

# Run install script
WORKDIR /install
RUN ./officeonline-install.sh

# Create Symlink for /opt/poco-${poco_version}-all
RUN ln -s /opt/poco-*/ /opt/poco
```

**/etc/docker/daemon.json**:
```
{
    "storage-driver": "overlay2"
}
```
